### ISSUE TITLE
SSC - Coilfang Fathom-Witch

### ISSUE THREAD

**Issue by thk88** [elysium-project/tbc-bug-tracker#1065]
**Summary:** 
The Coilfang Fathom-Witch are using Dominate on the first on their aggro table instead of the second.

**Steps to Reproduce:** 
Go to SSC and pull the pack guarding either the tunnel to Leo or Morogrim.

**Expected Results:** 
The Fathom-Witch should be dominating the second on their aggro table and not their first. 

**Actual Result:**
The first on the aggro table gets dominated.

**Additional Information:**
Since the tank easily gets dominated, the adds run to the raid and starts knocking everyone into the water, causing the adds to path down into the water and crash the instance.
Since the water path issue isn't an easy fix, this definitely will make it easier to fare in SSC.
Here's a link for the information on it being the second on the aggro table (search for Pack type 4): [link](https://wowwiki.fandom.com/wiki/Serpentshrine_Cavern)

I can't find anything in the official changelog regarding those mobs, except that the pack size is decreased from 4 Serpentguards to 2, so it's my belief that this is a bug.

**Comment by Hellishcrew** [comment]
atm its really always the first target which gets controlled. But since you know its going to happen you can control it. Just put a second tank on each Witch and let the second Tank taunt when the first one gets controlled (until it gets fixed). Also for the Water path issue: It seems it only crashes when Pets (WL/Hunter) crash into water, not players

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
