### ISSUE TITLE
Al'ar Tempest keep 

### ISSUE THREAD

**Issue by buckshaq** [elysium-project/tbc-bug-tracker#1089]
The issue we see is that after a quill ability Al'ar will go back to one of the middle platforms ( most peope would call this platforms 2 and 3)  This wipes the raid because there is no way for a tank to get back into position after having to jump down during the Quill.

The intended result is Al'ar always returns to one of the two platforms closest to the ramps. ( most often called platforms 1&4). 

We will post footage soon of the boss flying back to platform 3 instead of 1&4

if our math is correct here. assuming we get lucky, we only have roughly a 12.5% chance of reaching phase two because of the first bug. The second bug is pretty rough but We believe the boss could be killed still in theory. still needs addressed though. I suspect the intercept bug will be pretty hard to fix.

**Comment by ArisTheGod2** [comment]
**Summary:**
Al'ar encounter not working as intended. After quil ability Al'ar goes to the "middle" platforms resulting in a raid wipe due to the fact that tank cannot get to the middle position having jumped down during the Quil. If Al'ar has no tank in position he casts Flame Buffet on the whole raid which is the root cause of the wipe.

**Expected Results:**
Al'ar should be going to the platforms closest to the ramps, This way, the tank can get in potion in time. The raid will not get hit with flame buffet and will have a chance at killing the boss.

**Actual Result:**
As soon as Al'ar casts Quill, the tanks jump down and Al'ar returns to ANY RANDOM platform. He can go to the far platforms (not the ones closest to the ramp). Guaranteeing a raid wipe in that case.

**Additional Information:**
https://www.twitch.tv/videos/516379551

VoD of an attempt.

**Comment by Ziggy-QA** [comment]
@ArisTheGod2 I believe this a pre-nerf mechanic for Al'ar, but i'll have to look into it.

The idea is to have multiple tanks ready to pick up a'lar, or use to adds to get launched towards the other platform and slowfall to prevent damage.

I'll do some research and confirm whats intended.

**Comment by buckshaq** [comment]
you cannot have multiple tanks up on the platforms immediately after Quill. the tanks get basically 1 shot if they stay on the platforms

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.

**Comment by Ziggy-QA** [comment]
@buckshaq Yes I misunderstood what was actually happening here, my apolgies.

This has been fixed and pushed to live, as mentioned above!

**Comment by ArisTheGod2** [comment]
@Ziggy-QA @IvanDanshin Thank you guys so much! You guys are awesome , much love!
