### ISSUE TITLE
Heroic Blood Furnace - Felguard Brute

### ISSUE THREAD

**Issue by Dragomil** [elysium-project/tbc-bug-tracker#197]
(http://db.hellfire-tbc.com/?npc=18894) melee and (http://db.hellfire-tbc.com/?spell=18072) Uppercut ability hits extremely hard. Was told by Flame to report this. My character was a full T3 tank specced Paladin.

![wowscrnshot_062418_163226](https://user-images.githubusercontent.com/2252015/41820533-94ff7034-77d3-11e8-8e75-c14a0954ef56.jpg)

![wowscrnshot_062418_163444](https://user-images.githubusercontent.com/2252015/41820538-98f68894-77d3-11e8-88ac-40c9a98b29f9.jpg)

**Comment by Nadlek** [comment]
i like that someone reports THIS as bug ^^
pre nerf heroics were harder than kara and those dmg values seem right! in you current gear when you pulled one of the grps downstairs without cc you should have been globaled, if that didn't happen (again, if you didn't use cc and heavy cd even against one felguard) the dmg values are off and need readjustment
i'll only comment here because i find it funny, ppl gettin suprised by the pre nerf heroic values :)

**Comment by RainElysium** [comment]
Working as intended. Although values were slightly lower than they should be for Heroic after proper investigation.
