### ISSUE TITLE
Lord Solanar Bloodwrath (25223)

### ISSUE THREAD

**Issue by Wafhien2** [elysium-project/tbc-bug-tracker#260]
Seems like he is on  his day off .
![wowscrnshot_083018_214302](https://user-images.githubusercontent.com/35670554/44875180-b6b5a280-ac9d-11e8-9164-4194e6a2c984.jpg)
he is mandatory for many pla quest.

**Comment by evolve2** [comment]
I'm guessing it's due to the weird game version state of this beta realm. This NPC was brought here at 2.4 patch while moving the previous NPC (Lady Liadrin) to Shattrath. On this realm Lady Liadrin is still in Silvermoon City, bottom level of this same building (jump down the red hole seen on the above picture in the center of the room).

From Wikipedia: "After the betrayal of Kael'thas to the Burning Legion, the prince led a brief attack on Silvermoon to spirit away M'uru to the Sunwell. Lady Liadrin traveled to Shattrath City in order to secure a new source of power for the order, leaving Solanar to take her place in Silvermoon. As Liadrin's second-in-command, Solanar took over the duties of training aspiring Blood Knight Masters in her stead."
