### ISSUE TITLE
Hunter Pet Issues

### ISSUE THREAD

**Issue by RogueArc** [elysium-project/tbc-bug-tracker#332]
60-63 Hunter - Pet (60 Sporebat)
Pet does not begin attack on Defensive, does attack if Hunter is hit by mob. (by design?)
Pet does not regen Health very fast (4200 HP) when out of combat; neither does Hunter (Health and Mana)
Pet does not Follow after attacking on Aggressive or Defensive, can not return. It tries, turns and one steps, but then returns to fighting.
Pet 63, food 55, does not move pet from Content to Happy always. Takes two feedings to reach Happy. (by design?)

**Comment by ZicoQA** [comment]
I have tested this pet and it looks fine.

Point by point:

Pet does not begin attack on Defensive, does attack if Hunter is hit by mob. (by design?)
Yes by design. If a pet is on Defensive he will only attack if hunter gets attacked or player clicks the attack button.

Pet does not regen Health very fast (4200 HP) when out of combat; neither does Hunter (Health and Mana) 
Regen is fine and maybe you had a debuff or something. Please show proof that yours is slow.

Pet does not Follow after attacking on Aggressive or Defensive, can not return. It tries, turns and one steps, but then returns to fighting.
Again by design if pet is on defensive and you ask him to follow you, after the command he will go back to his defensive posture, same happens on aggressive. For the pet follow he will only do if you change his stance to passive first and then click on follow.

Pet 63, food 55, does not move pet from Content to Happy always. Takes two feedings to reach Happy. (by design?)
Tested this and only took 1 food to change pet mood. Remember feeding the pet is a buff and it he will only change mood if he has eaten the whole buff without getting interuped (by combat or whatever).
