### ISSUE TITLE
 [Bloodgem Crystals] Not dropping the item [Bloodgem Shard]

### ISSUE THREAD

**Issue by jim-arbete** [elysium-project/tbc-bug-tracker#510]
**Summary:** 
Killed many "Sunfury Magister" and they dont drop the quest item.

**Steps to Reproduce:** 
Kill "Sunfury Magister"

**Expected Results:** 
Drop [Bloodgem Shard]

**Actual Result:**
 [Bloodgem Shard] Doesnt drop

**Additional Information:**

**Comment by Ziggy-QA** [comment]
![image](https://user-images.githubusercontent.com/45450044/50553930-7297d600-0c6e-11e9-8a22-74f5f9b7a808.png)
Hi @jim-arbete. Looks like I was able to get it on my 5th kill. Are you still having this issue?

Since this is clearly working as intended, this issue will now be closed. But please do post more info if your still experiencing this issue.
