### ISSUE TITLE
Warlock pet alone mob kill don't tag the warlock

### ISSUE THREAD

**Issue by Skaelle** [elysium-project/tbc-bug-tracker#549]
**Summary:** 
When a pet kills a mob without the warlock hit him, we can not loot the mob that the pet killed. As if the mob was not tag for the warlock. If the warlock hits the mob before it dies it works fine.
**Steps to Reproduce:** 
Just lets a pet kill alone a mob.

**Additional Information:**
Trying with the void and felguard on grey mob (at the Stockade  SW and Elween forest)

**Comment by PeppyDolphin** [comment]
It is possible to have the pet fight one mob while the Hunter attacks another. Note: the Hunter will not gain loot or experience from a mob that the pet kills solo. This is a deliberate decision by Blizzard, not a bug. If you intend on pulling multiple mobs and having your pet kill one or more of them while you focus on others, it would be best to try to get at least one shot or hit on each of the mobs and then allow your pet to do its work on them. 
https://wow.gamepedia.com/Hunter_pet
This is the same case for warlocks also.

**Comment by PeppyDolphin** [comment]
So I did double check this and have been looking into this. It should not be like that on the live version and that is a bug actually instead of it being a bug on TBC PTR not getting loot. I am going to close ticket and open one under the classic section for correct placement. Thank you for bringing this to our attention.
