### ISSUE TITLE
Quest: Improper Burial [10913]

### ISSUE THREAD

**Issue by kedross** [elysium-project/tbc-bug-tracker#582]
Two Issues:

NPC Slain Sha'tar Vindicators [21859] do the courtesy of greeting you, even though they're dead.
NPC Auchenai Warriors [21852] respawn timer seems incredibly short (a matter of a few seconds), and they do not seem to be dropping any loot native to Humanoids or loot at all.

**Comment by McMittens** [comment]
21859 greet the player when clicked on, this is not intended.
21852 have a 10 seconds respawn timer and no loot table assigned.
![22](https://user-images.githubusercontent.com/46020700/52359374-1331a080-2a3a-11e9-9aa7-fb057d89aaf8.PNG)
There's no alive Vindicators [21858] in that area to fight Auchenai Warriors [21852]

**Comment by McMittens** [comment]
So the Vindicators should fight the Auchenai Warriors, but currently the Vindicators are not spawned, so the Warriors are not bound in combat. I don't think there's necessarily a problem with the Warriors loot table, since they would be very easy to grief with the short respawn and Vindicators help.
