### ISSUE TITLE
Entangling Roots Exploit/Bug

### ISSUE THREAD

**Issue by Medecc6** [elysium-project/tbc-bug-tracker#589]
**Summary:** Whenever using Entangling Roots, if you walk out of range then back in range, damage dealt will not remove the roots.

**Steps to Reproduce:** Cast Entangling Roots, walk out of range (Wrath or Moonfire range, so about 30 yards), move back into range and cast damage spells.

**Expected Results:** Roots go away.

**Actual Result:** Roots are not triggered by the damage.

**Additional Information:** It doesn't seem to always happen, and I haven't gotten it to work on anything except for the Prairie Wolf(s) around Bloodhoof Village so far

ADDENDUM: I've noticed that you don't have to walk out of range to trigger this, Entangling Roots sometimes just wont go away. (I used roots on a Palemane Tanner and did not see them go away, nor the debuff.)

ADDENDUM 2: I believe it might be the DoT that Moonfire applies that doesnt trigger Entangling Roots, however direct damage from my Wrath or Moonfire will trigger it.

**Comment by McMittens** [comment]
I wasn't able to reproduce this. 
Entangling Roots has a chance to break upon taking damage, which can be caused by it's own damage, and there's no limiting damage threshold where it will always break, so it's possible for the spell to be on for the entire duration.
Distance to the enemy didn't influence when the roots would break, they also broke on the dot from moonfire.

If you have any additional info to reproduce the issue, please comment below!

**Comment by Medecc6** [comment]
I'm going to see if I can get video footage of this happening some time today, if I cannot find this happening to me again, thank you for your good work.

**Comment by Medecc6** [comment]
The first half of the footage is still uploading and probably wont get shown until tomorrow, but here's the second half. [https://www.youtube.com/watch?v=xVDMqlDU_MA](url)

**Comment by McMittens** [comment]
Thank you for your commitment to the issue!

![22](https://user-images.githubusercontent.com/46020700/52137884-f5d09100-264b-11e9-8f7f-81e337d22dd5.PNG)
![23](https://user-images.githubusercontent.com/46020700/52138133-98890f80-264c-11e9-8ffe-4a1eb7192994.PNG)
I tested it both with Rank 1 and Rank 2 and was able to break Entangling Roots prematurely with only the DoT from moonfire.

It might not happen often since it's rather unlikely to happen, but it's working as intended.

**Comment by Medecc6** [comment]
Thank you!!
