### ISSUE TITLE
Karazhan Bug report 28-02-2019

### ISSUE THREAD

**Issue by elysiumgrill** [elysium-project/tbc-bug-tracker#646]
**Summary:** 
This will be a compilation of several issues as some seem linked and I am extremely tired while writing this.

after wipe on Aran nameplates turn into "unknown" and all social chats /say /guild /party /raid etc become invisible but general chats and so on are still there

upon wipe group could not enter instance when ghost. Relog reset the ID happened at skeleton mages near opera

*Big Bad Wolf moving considerably slower than supposed to 

*repeated game crashes (happens everywhere but especially after opera for some reason)

*repeated crashes on Aran (seems to be after first blizzard phase each time) *possibly resolved by disabling all addons.
Addons: Omen, quartz, DBM
will have to figure out which one is causing it specifically

shoutout to @Mcmittenz for being the best GM :)

- Grill

**Steps to Reproduce:** 
Enable/disable the addons to figure out which is causing crashes
Figure out exactly what is happening when ghosts not allowed into karazhan. (more wiping?)

**Expected Results:** 
Pinpointing sources of bugs

**Actual Result:**

**Additional Information:**
Once again I apologize for the slightly messy report. I'll try to follow the protocol better next time. I just wanted to do this before I forget.

**Comment by MrMarvin** [comment]
Also there appears to be a glitch with the wolfs fear effect, pushing players outside the stage. As seen in a recent test run here: https://www.twitch.tv/schnoppers/clip/EncouragingVictoriousMeerkatDendiFace?filter=clips&range=7d&sort=time

**Comment by Ziggy-QA** [comment]
We are aware of some instability issues with Karazhan. However, Thank you for your report regardless. This info will help is pinpoint the cause. As for "Big bad Wolf" He was originally way too fast, and the fix was kinda wrong. Now he is too slow. We are working on this aswell.

I suggest that you play with your addon settings and try and optimize memory allocation with your client. It seems that this only happens with only a few clients and system specs. Not everyone gets the crashing problem, so its very hard to test. For example I have run all kinda of different addons and never had a problem myself, but every system is different.

Investigation is ongoing.
