### ISSUE TITLE
Black Qiraji Battle Tank

### ISSUE THREAD

**Issue by Tercoil** [elysium-project/tbc-bug-tracker#674]
**Summary:** 
Black Qiraji Battle Tank (21176) doesnt have instant cast

**Steps to Reproduce:** 
Give yourself this mount and mount up
**Expected Results:** 
Instant mount up
**Actual Result:**
Casting timer 3 seconds
**Additional Information:**

**Comment by Ziggy-QA** [comment]
@Tercoil Black Qiraji Battle Tank is not even supposed to have an instant cast in vanilla. It still had an cast time, however did not quite have the same casting mechanics as real mount. This included having no cast animation, being unable to cast it, only able to be dismounted by dismissing the buff.

See here:
![image](https://user-images.githubusercontent.com/45450044/59079559-53067880-88b2-11e9-914f-225f55f1d7a8.png)

https://web.archive.org/web/20071221155252/http://wow.allakhazam.com/db/item.html?witem=21176;page=1;howmany=50#m114947239915026

The is a snippet of a Alakhazam forum post of players stating that it is not supposed to behave this way. The reason it is an instant cast on private servers is because of insufficent research when developing the nost core. The instant cast was merely a rumor going around when the mount was first out. These statements date back to  Mar 1st 2006 which was patch Patch 1.9.4. Meaning at most, it could have been like this for a month before they fixed it.
