### ISSUE TITLE
Mailbox clicking issue

### ISSUE THREAD

**Issue by ilyysae** [elysium-project/tbc-bug-tracker#734]
I can't use my mailbox, when I try to click on mailbox my game stops like it lost connection.

**Comment by Tsukumogamiru** [comment]
Same problem. Seems like I loose connection to server every time I check my mailbox. I can't Interact with npcs when this happens and every player just stay or run at the same place. I have this problem with only one character. I guess the reason is that I had a bid on the AH before DB copying, so some issues occured during the process.

**Comment by Ziggy-QA** [comment]
Due to being in a large guild. Will reference #745 and close this issue.
