### ISSUE TITLE
Corrupted Sabers quest can't be completed

### ISSUE THREAD

**Issue by Kunchy** [elysium-project/tbc-bug-tracker#800]
**Summary:** 
Corrupted Sabers in Felwood can't be completed. 
**Steps to Reproduce:** 
Once you get to the corrupted moonwell and realese the cat from your quest item at it. You escort it back to Bloodvenom Post to the the NPC giver Winna Hazzard. There the cat should be able to talk to you to mark the quest as completed and then you talk to the NPC quest giver to turn in it. 
**Expected Results:** 
 Once you reach the NPC quest giver Winna Hazzard in Bloodvenom Post the cat should be able to interact with the player to mark it complete. 
**Actual Result:**
The cat won't interact so the quest can't be completed. 
**Additional Information:**

**Comment by andersleet** [comment]
I just attempted to summon the cat IN the corrupted moonwell and it will not transform. It just stands next to me like a normal non-combat pet. I cannot verify that the quest cannot be turned in since I haven't gotten that far along. I am going to attempt one more time by abandoning and reaccepting the quest but it seems to be broken.

**Comment by andersleet** [comment]
Stood in the pool after abandoning the quest and reaccepting it; same result of the cat not turning into a sabercat. Cat does not transform and dies after about 5 minutes from being summoned.

**Comment by IvanDanshin** [comment]
Fixed. Thanks for report!
