### ISSUE TITLE
Undercity Gravity issues

### ISSUE THREAD

**Issue by bush5150** [elysium-project/tbc-bug-tracker#842]
**Summary:** 
Players in Undercity are experiencing strange falls from heights.  Players will fall and the game will put them back where they fell and sometimes higher, leading to death.  Sometimes this loops, leading players to get really elevated places (I managed to get up into the rafters and walk around the outer circle).

**Steps to Reproduce:** 
Jump off any place of height in Undercity

**Expected Results:** 
Player lands firmly on the ground. 

**Actual Result:**
Players fall several times, progressively getting higher until death. 
Here's a short video of the effect:
https://youtu.be/3EJuWIE64sc

**Additional Information:**

**Comment by Ziggy-QA** [comment]
This is due to the newly implemented feature that is supposed to port players back to the surface if they happen to fall under the world. The range is still being adjusted to prevent issues like this, but please be patient until its fully functional. We have recently applied a fix that increases the range and we hope it will alleviate this issue.

**Comment by bush5150** [comment]
I don't know.  This just happened falling off the bridge in UC, stuck in a perpetual loop.  
https://youtu.be/CgUcunqgVsM
