### ISSUE TITLE
Fishing Schools aren't working

### ISSUE THREAD

**Issue by bush5150** [elysium-project/tbc-bug-tracker#843]
**Summary:** 
When fishing in schools, the bobber will make noise and bounce, but only rewards player with a skill point with no fish.  

**Steps to Reproduce:** 
Fish where there are schools, such as sagefish school in Silverpine or deviate fish school in Barrens.

**Expected Results:** 
Player catches the special fish, like sagefish or deviate fish. 

**Actual Result:**
Player is rewarded a skill point, but no fish upon clicking the bobber.

**Additional Information:**

**Comment by SenjiuKanuba** [comment]
If the additional information helps when tackling the issue:
I fished the floating debris in ratchet a bit yesterday and most of the time the actual result as described above happened but I got a tightly sealed trunk with some linen bolts in it once, which would be the expected result. So it does work sometimes (that was maybe one try out of 20 that worked)

**Comment by bush5150** [comment]
I received 1 deviate fish in a school earlier.  Same for a trunk in floating debris in Silverpine.  That's only a few instances in several schools.  Most of the time, it's nothing.

**Comment by Watsegwan** [comment]
Yes I have the same problem, the 1st time I throw the bobbler in a fish school of zangarmarsh it drop the special fish, then every other tries doesn't give me anything.
It just opens an empty looting window.
It feels like fishs school are considered as a mob loot that you can't loot twice because it as already been looted.

I like fish, I want more fish please !
