### ISSUE TITLE
Curator not scripted correctly

### ISSUE THREAD

**Issue by Hellishcrew** [elysium-project/tbc-bug-tracker#879]
We went Kara this Evening and made it till Curator but on this Server he has a damage reduction shield in P1 which reduces the damage taken by 90%. He never had that back in Blizzards TBC (I played back than and we killed the Boss ~ 2 weeks after TBC launched). The shield makes it almost impossible to kill this Boss. We ran with a full T3 equipped group with Shamans for BL and both groups and we did not manage to get the Boss below 50% HP in 2 Evocation Phases although we fully commited with Flasks, Food and so on. Also i searched the web and did not find a single guide which mentions this shield. The shield has to be removed from him in order to make him "kill able".

**Comment by Ziggy-QA** [comment]
@Hellishcrew 

The ability that reduces damage by 90% on curator is called "Astral Armor" and did indeed exist up until patch 2.0.8. This falls into "Pre-Nerf" state which is currently what the Karazhan on this server is, and will not be changed until he is defeated by all progression raiding guilds multiple times, or until 2.1, whichever comes first.

[Proof: Wowiki Article "The Curator" Revision as of 20:01, January 1, 2007] (https://wowwiki.fandom.com/wiki/The_Curator?oldid=394424)

If you wanted easy karazhan runs on launch, then this server probably isn't the best for that.

**Comment by Hellishcrew** [comment]
https://wowwiki.fandom.com/wiki/Patch_2.0.8

Fixed several display issues with the arena battle final scoreboard.

No Curator nerf mentioned

**Comment by Ziggy-QA** [comment]
@Hellishcrew 

Many times changes arent documented on patch notes if it did not affect a large portion of the playerbase.

Since your so adamant that you have perfect memory and insist that curator did not have astral armor, here is a archived web page of one of the first guides for karazhan including the information.

https://web.archive.org/web/20070219154732/http://www.ampwow.com/wow/viewNewCreatures/15691-The+Curator.php!default=strat

And I can assure you the boss is possible. You dont need me to tell you that you need to maximize your burst dps during the invocation phases. It also requires actual gear from heroic vendors and other bosses from karazhan.

**Comment by Hellishcrew** [comment]
Our group was full of players with full T3 gear which is in 90% of the cases better than most gear you can get till Karazhan. Also the ppl cleared Naxx severell times so they know what they were doing. I mean if you really want to keep it that way ok (we will kill the boss somehow sooner or later) but you will kill all posible random groups with this cause for "casual" players the boss is unkillable.

**Comment by Ziggy-QA** [comment]
@Hellishcrew 

That comment was most likely submitted after it was removed. There was most likely around 2-3 ids with this ability implemented.

Here is even *further* discussion on this topic. This is Karazhan pre-nerf. Before anyone knew anything about the game, and people still managed to down this boss pre-nerf.
https://github.com/Looking4Group/L4G_Core/pull/13

We don't intended make Karazhan "Casual" on release. If you feel like your meet the gear-check adequately, then perhaps something else is in question. Just because you cant beat a boss doesn't mean you should immediately cry broken. It should be more than possible to beat Curator in this state especially since class balance is 2.4

This issue will remain closed, but the mechanic will only be changed if it stops progression of any guild for an unnecessary amount of time.
